import type { Message } from "@/app/app/interfaces";
import {
  formatModelProvenanceLabel,
  resolveMessageModelProvenance,
} from "@/lib/chat/modelProvenance";

function messageWithModel(
  modelDisplayName: string,
  overriddenModel: string
): Message {
  return {
    nodeId: 10,
    messageId: 10,
    message: "answer",
    type: "assistant",
    files: [],
    toolCall: null,
    parentNodeId: 9,
    packets: [],
    modelDisplayName,
    overridden_model: overriddenModel,
  };
}

describe("message model provenance", () => {
  it("uses the model stored on the answer, not the current chat selector", () => {
    const providerLookup = new Map([
      ["GPT-5.2", "openrouter"],
      ["openai/gpt-5.2", "openrouter"],
      ["claude-sonnet-4-5", "anthropic"],
    ]);
    const message = messageWithModel("GPT-5.2", "openai/gpt-5.2");

    expect(resolveMessageModelProvenance(message, providerLookup)).toEqual({
      displayName: "GPT-5.2",
      modelName: "openai/gpt-5.2",
      provider: "openrouter",
    });
  });

  it("renders provider and model as an explicit generated-by label", () => {
    expect(formatModelProvenanceLabel("openrouter", "GPT-5.2")).toBe(
      "Generated by OpenRouter · GPT-5.2"
    );
  });

  it("does not invent provenance for legacy messages without model metadata", () => {
    const message = messageWithModel("", "");
    expect(resolveMessageModelProvenance(message, new Map())).toBeNull();
  });
});
