import type { Message } from "@/app/app/interfaces";
import { getProvider } from "@/lib/languageModels";

export interface MessageModelProvenance {
  displayName: string;
  modelName: string;
  provider?: string;
}

export function resolveMessageModelProvenance(
  message: Message,
  providerLookup: ReadonlyMap<string, string>
): MessageModelProvenance | null {
  const displayName = message.modelDisplayName?.trim();
  const modelName = message.overridden_model?.trim();
  const effectiveDisplayName = displayName || modelName;
  const effectiveModelName = modelName || displayName;
  if (!effectiveDisplayName || !effectiveModelName) return null;

  return {
    displayName: effectiveDisplayName,
    modelName: effectiveModelName,
    provider:
      providerLookup.get(effectiveModelName) ??
      providerLookup.get(effectiveDisplayName),
  };
}

export function formatModelProvenanceLabel(
  provider: string | undefined,
  displayName: string
): string {
  const modelLabel = displayName.trim();
  if (!provider) return `Generated by ${modelLabel}`;
  return `Generated by ${getProvider(provider).productName} · ${modelLabel}`;
}
