"""Add CHUNKED to UserFileStatus

Chunk production and indexing are separable: a file can have its regulatory
chunks written and reviewable while nothing has reached the search index yet.

Revision ID: 6df58c46ade5
Revises: f7b2e4c6a8d1
Create Date: 2026-08-19 16:41:07.699818

"""

import sqlalchemy as sa
from alembic import op

revision = "6df58c46ade5"
down_revision = "f7b2e4c6a8d1"
branch_labels = None
depends_on = None

TABLE = "user_file"
COLUMN = "status"
CONSTRAINT_NAME = "ck_user_file_status"

# BATCH_PROCESSING predates the Python enum but is still permitted by the live
# constraint; dropping it here would reject rows this migration does not own.
OLD_VALUES = (
    "PROCESSING",
    "INDEXING",
    "COMPLETED",
    "SKIPPED",
    "FAILED",
    "CANCELED",
    "DELETING",
    "BATCH_PROCESSING",
)
NEW_VALUES = OLD_VALUES + ("CHUNKED",)


def _drop_status_check_constraint() -> None:
    """Drop the existing CHECK constraint on user_file.status.

    The constraint name is auto-generated by SQLAlchemy and unknown,
    so we look it up via the inspector.
    """
    inspector = sa.inspect(op.get_bind())
    for constraint in inspector.get_check_constraints(TABLE):
        if COLUMN in constraint.get("sqltext", ""):
            constraint_name = constraint["name"]
            if constraint_name is not None:
                op.drop_constraint(constraint_name, TABLE, type_="check")


def upgrade() -> None:
    _drop_status_check_constraint()
    in_clause = ", ".join(f"'{value}'" for value in NEW_VALUES)
    op.create_check_constraint(CONSTRAINT_NAME, TABLE, f"{COLUMN} IN ({in_clause})")


def downgrade() -> None:
    # Chunked files have rows but no projection; PROCESSING re-runs ingestion for
    # them, which is the only safe pre-CHUNKED state.
    op.execute(f"UPDATE {TABLE} SET {COLUMN} = 'PROCESSING' WHERE {COLUMN} = 'CHUNKED'")
    _drop_status_check_constraint()
    in_clause = ", ".join(f"'{value}'" for value in OLD_VALUES)
    op.create_check_constraint(CONSTRAINT_NAME, TABLE, f"{COLUMN} IN ({in_clause})")
