services:
  postgres:
    container_name: customs-db-dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
