OPENROUTER_RERANK_URL = "https://openrouter.ai/api/v1/rerank"

MAX_RERANK_CANDIDATES = 100
MAX_RERANK_DOCUMENT_BYTES = 16 * 1024
MAX_RERANK_DOCUMENT_TOKENS = 4_096
MAX_RERANK_TOTAL_BYTES = 512 * 1024
MAX_RERANK_TOTAL_TOKENS = 100_000
MAX_RERANK_REQUEST_BYTES = 576 * 1024
MAX_RERANK_REQUEST_TOKENS = 120_000

RERANK_CONNECT_TIMEOUT_SECONDS = 2.0
RERANK_READ_TIMEOUT_SECONDS = 8.0
RERANK_WRITE_TIMEOUT_SECONDS = 5.0
RERANK_POOL_TIMEOUT_SECONDS = 2.0

RERANK_CIRCUIT_FAILURE_THRESHOLD = 3
RERANK_CIRCUIT_COOLDOWN_SECONDS = 60.0
RERANK_CIRCUIT_MAX_COOLDOWN_SECONDS = 300.0
