OPENROUTER_RERANK_URL = "https://openrouter.ai/api/v1/rerank"
SILICONFLOW_RERANK_URL = "https://api.siliconflow.com/v1/rerank"
OPENROUTER_CHAT_COMPLETIONS_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_LUNA_RERANK_MODEL = "openai/gpt-5.6-luna"
OPENROUTER_CHAT_RERANK_MODELS = frozenset({OPENROUTER_LUNA_RERANK_MODEL})

MAX_RERANK_CANDIDATES = 100
MAX_RERANK_DOCUMENT_BYTES = 16 * 1024
MAX_RERANK_DOCUMENT_TOKENS = 4_096
MAX_RERANK_TOTAL_BYTES = 512 * 1024
MAX_RERANK_TOTAL_TOKENS = 100_000
MAX_RERANK_REQUEST_BYTES = 576 * 1024
MAX_RERANK_REQUEST_TOKENS = 120_000
RERANK_TOKEN_SAFETY_MARGIN_PERCENT = 10

MAX_CHAT_RERANK_CANDIDATES = 32
MAX_CHAT_RERANK_DOCUMENT_BYTES = 2_048
MAX_CHAT_RERANK_DOCUMENT_TOKENS = 2_300
MAX_CHAT_RERANK_TOTAL_BYTES = 64 * 1_024
MAX_CHAT_RERANK_TOTAL_TOKENS = 72_100

RERANK_CONNECT_TIMEOUT_SECONDS = 2.0
RERANK_READ_TIMEOUT_SECONDS = 20.0
RERANK_WRITE_TIMEOUT_SECONDS = 5.0
RERANK_POOL_TIMEOUT_SECONDS = 2.0

RERANK_CIRCUIT_FAILURE_THRESHOLD = 3
RERANK_CIRCUIT_COOLDOWN_SECONDS = 60.0
RERANK_CIRCUIT_MAX_COOLDOWN_SECONDS = 300.0


def uses_chat_completion_reranking(model: str | None) -> bool:
    return model in OPENROUTER_CHAT_RERANK_MODELS
